### ISSUE TITLE
No matching patch for termsrv.dll

### ISSUE THREAD

**Issue by macleysousa** [geissbuehler/TermsrvPatcher#1]
**Error:** _No matching patch for termsrv.dll found in patchfile 'Patches.txt', edit 'Patches.txt' or enter patches manually_

**Comment by geissbuehler** [comment]
I'm sorry, this is the intended behaviour. I do not want to put my GitHub account at risk and do not include valid patches with the project. You will have to search for patches yourself. I even hesitate to include a link in this response....
