### ISSUE TITLE
File used by another process. 

### ISSUE THREAD

**Issue by Mr-Pingu** [geissbuehler/TermsrvPatcher#2]
Patch on line 13 in 'Patches.txt' indicates unpatched termsrv.dll
Automatic patching enabled: Matching patch for termsrv.dll in patchfile 'Patches.txt' found on line 13
Stopping TermService... Done
Patching termsrv.dll
System.IO.IOException: The process cannot access the file 'C:\WINDOWS\system32\termsrv.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at TermsrvPatcher.Patcher.Patch(List`1 patch) in G:\Meine Ablage\Projects\TermsrvPatcher\TermsrvPatcher\Patcher.cs:line 356
   at TermsrvPatcher.MainWindow.worker_DoWork(Object sender, DoWorkEventArgs e) in G:\Meine Ablage\Projects\TermsrvPatcher\TermsrvPatcher\MainWindow.xaml.cs:line 334
Old status: Unpatched
Patch on line 13 in 'Patches.txt' indicates unpatched termsrv.dll
Automatic patching enabled: Matching patch for termsrv.dll in patchfile 'Patches.txt' found on line 13
New status: Unpatched

**Comment by geissbuehler** [comment]
This means that after stopping the Remote Desktop Service still another process is locking termsrv.dll. Please stop the service manually and make sure no other process is locking it before trying again. Maybe I will implement a more helpful error message for this situation.

**Comment by Mr-Pingu** [comment]
Will it be possible to patch the termsrv.dll in another location?
I cannot get this patcher to work but when I do it manually it works magically;
1. Take ownership
2. Give myself (User) Full Control of Termsrv.dll
3. Copy Termsrv.dll to desktop
4. Edit with HEX editor
5. Kill termservice
6. Rename Termsrv.dll in System32 folder to Termsrv.dll.bak.[date]
7. Copy Termsrv from desktop to System32 folder
8. Start Termservice

But somehow this patcher doesn't work and cannot find out why it is strugling. Do you have some kind of persistent error log?

**Comment by geissbuehler** [comment]
Please stop termservice manually and use Sysinternals Process Explorer to find the process with a handle to C:\Windows\System32\termsrv.dll and kill the process. See https://helpcenter.gsx.com/hc/en-us/articles/115015880627-How-to-Identify-which-Windows-Process-is-Locking-a-File-or-Folder for details. After the process is killed, patching should succeed.

If you want to modify the path to termsrv.dll you have to change this [code line](https://github.com/geissbuehler/TermsrvPatcher/blob/df4efd986bcc2b94dbb71f1ff3242517b1719fd7/TermsrvPatcher/Patcher.cs#L233). If you don't have Visual Studio 2019 installed for debugging, you can download the Community Edition from https://visualstudio.microsoft.com/vs/.

**Comment by geissbuehler** [comment]
It turns out that running Process Explorer as Administrator is not enough to see for example the handle of the termservice process svchost.exe. I had to run Process Explorer at least as System user. I propose to use [NSudo](https://github.com/M2Team/NSudo/releases/latest) to run the Process Explorer as TrustedInstaller to be able to find ALL handles to termsrv.dll
