### ISSUE TITLE
Stopping TermService may take forever

### ISSUE THREAD

**Issue by geissbuehler** [geissbuehler/TermsrvPatcher#5]
On some systems stopping the Remote Desktop Services fails and the service status remains in the stopping state forever. The patcher also just waits forever for the stopped service state. After a reboot stopping the service usually succeeds. Also manually killing the corresponding svchost.exe process solves the problem and allows successful patching.
A timeout for stopping the service should be implemented and the root cause for this behavior of the service should be identified. A workaround like automatic rebooting should be added for patching via remote desktop connection to prevent making the system unreachable.

**Comment by skunkie** [comment]
The root cause is that UmRdpService depends on TermService. We should stop UmRdpService-> stop TermService -> do the patch work -> start TermService -> start UmRdpService.
